import json

title = ['I “only” use R for descriptive stats — and that’s OK',
         "Machine Learning Bites",
         "Cookiecutter Data Science",
         "Complete Guide to Regressional Analysis Using Python",
         "Ultimate R Cheat Sheet",
         "Setting Up a New Project",
         "TensorFlow Examples",
         "100+ Data Science, Deep Learning, AI & Machine Learning Cheat Sheet PDF",
         "ML-For-Beginners",
         "Python resources for everybody",
         "Python Data Science Handbook",
         "Learn Git Branching",
         "RegexOne",
         "R for Data Science",
         "Introduction to Probability for Data Science",
         "Monet CycleGAN Tutorial",
]

author =["David Keyes",
          "Rishabh Anand",
          "-",
          "Brandon Morgan",
          "-",
          "Greg Wilson",
          "many",
          "Insane",
          "microsoft",
          "-",
          "Jake VanderPlas",
          "-",
          "RegexOne",
          ["Hadley Wickham","Garrett Grolemund"],
          "Stanley H. Chan",
          "Amy Jang"
]

format = ["blog",
          "guide",
          "guide",
          "guide",
          "cheat sheets",
          "guide",
          "tutorial",
          "cheat sheets",
          "tutorial",
          "collection",
          "book",
          "tutorial",
          "tutorial",
          "book",
          "book",
          "tutorial",
]

description = ["Useful blog for a variety of Rstats users",
            "General guide for understanding machine learning and some maths behind it",
            "guide for organising Python project code",
            "Guide relating to many different regressional methods",
            "compilation of R cheat sheets for data science",
            "step-through guide to initiate python software engineering project",
            "collection of jupyter notebook tensorflow tutorials",
            "collection of machine learning cheat sheets",
            "interactive github repo for beginner machine learning",
            "collection of python resources at many ranges of skill",
            "book for python data science",
            "interactive online tutorial to learn git branching",
            "interactive online tutorial to learn regex basics",
            "book to learn data science with R following industry best practices",
            "book covering different introductory probability methods including hypothesis testing and different distributions",
            "Tutorial for using tensorflow and CycleGANS in Python based on a Kaggle competition.",
]    

link = ["https://rfortherestofus.com/2018/12/descriptive-stats-r/",
        "https://www.notion.so/Machine-Learning-Bites-7c1675ecb587451e9caf793c68972276",
        "https://drivendata.github.io/cookiecutter-data-science/#cookiecutter-data-science",
        "https://towardsdatascience.com/complete-guide-to-regressional-analysis-using-python-bbe76b3e451f",
        "https://www.business-science.io/r-cheatsheet.html?utm_content=buffer74613&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer",
        "https://third-bit.com/2021/11/15/setting-up-a-new-project/",
        "https://github.com/aymericdamien/TensorFlow-Examples",
        "https://www.theinsaneapp.com/2020/12/machine-learning-and-data-science-cheat-sheets-pdf.html",
        "https://github.dev/microsoft/ML-For-Beginners",
        "https://learnbyexample.github.io/py_resources/",
        "https://jakevdp.github.io/PythonDataScienceHandbook/",
        "https://learngitbranching.js.org/",
        "https://regexone.com/",
        "https://r4ds.had.co.nz/",
        "https://probability4datascience.com/",
        "https://www.kaggle.com/amyjang/monet-cyclegan-tutorial"
]

language = ["R",
            "Python",
            "Python",
            "Python",
            "R",
            "Python",
            "Python",
            "Python",
            "Python",
            "Python",
            "Python",
            "Git",
            "Regex",
            "R",
            ["MATLAB","Python","Julia","R"],
            "Python",
]

key_themes = [["statistics","blog"],
            ["machine learning","algorithms","models"],
            ["project structures","organising code","project templates"],
            ["machine learning","regression","learning"],
            ["cheat sheet","shiny","rmarkdown","tidyverse"],
            ["project structures","organising code","project templates","software engineer"],
            ["tensorflow","mnist","machine learning","repo"],
            ["cheat sheet","machine learning","scikit-learn","tensorflow"],
            ["machine learning","beginners","repo","classification","nlp"],
            ["collection", "computer vision"],
            ["numpy","pandas","matplotlib","machine learning"],
            ["interactive","git","organising code"],
            ["nlp","text","interactive","language"],
            [ "project structures","rmarkdown","tidy data","tidyverse"],
            ["statistics","probability","distributions","regression"],
            ["gan","machine learning","tensorflow","keras","competition"],
]

difficulty = [3,
              7,
              7,
              8,
              8,
              7,
              10,
              10,
              10,
              10,
              10,
              5,
              5,
              9,
              10,
              10,
]

recommended_by = ["wtumber"] * 16

handle = ["@wtumber"] * 16

aboutme = ["data analyst and student at Solent University"] * 16





